version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - ./_static:/usr/src/app/_static
      - ./_media:/usr/src/app/_media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn soil_site_prj.wsgi:application --bind 0.0.0.0:8200"
    volumes:
      - ./:/usr/src/app/
      - ./_static:/usr/src/app/_static
      - ./_media:/usr/src/app/_media
    expose:
      - 8200    # ports 대신 expose 사용!
